#! /bin/bash

PATH="${SRCROOT}/Opensources/fmdb/"
REAL_DEVICE="FMDB_REAL_DEVICE"
SIMULATE_DEVICE="FMDB_SIMULATE_DEVICE"

REAL_PATH=${PATH}${REAL_DEVICE}
SIMULATE_PATH=${PATH}${SIMULATE_DEVICE}

echo ${OTHER_SWIFT_FLAGS}


