# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealmSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RealmSample

  pod 'Realm'
  target 'RealmSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RealmSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
